### ISSUE TITLE
Google Colab install geosnap error #184

### ISSUE THREAD

**Issue by swagluke** [oturns/geosnap#369]
#### Description of the bug
Trying to install geosnap on Google Colab but running into issue with "Building wheels for collected packages: tables"
I've tried following command to fix the issue but without any luck.
1. I've confirmed that tables is installed properly. (3.8.1.dev0) - `!pip install tables --upgrade`
2. Upgrading wheel and setuptools - `!pip install wheel setuptools pip --upgrade`
3. Upgrading cmake - `!pip install cmake --upgrade`

#### Environment 

- Operating system: Linux 9e7b8fb3f067 5.15.109+ #1 SMP Fri Jun 9 10:57:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

- Python version: Python 3.10.6

- Geosnap version: geosnap-0.11.0

#### Paste the code that reproduces the issue here:

```python
`!pip install geosnap`
```

#### Paste the error message (if applicable):
```python
Created wheel for pandana: filename=pandana-0.6.1-cp310-cp310-linux_x86_64.whl size=1851096 sha256=e524fa6c06a5d4fa2fa9ad88a8e770443f4db2dc6548d75e7a10f983be9af42f
  Stored in directory: /root/.cache/pip/wheels/e7/4b/71/360fe3ffe9d5822e4d35b07a9938f0b074056b43a0040b373a
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for tables (setup.py) ... error
  ERROR: Failed building wheel for tables
  Running setup.py clean for tables
Successfully built matplotlib cenpy pandana
Failed to build tables
ERROR: Could not build wheels for tables, which is required to install pyproject.toml-based projects
```

**Comment by knaaptime** [comment]
thanks for raising this, though I honestly don't think there's a fix on our end. Ultimately this is an issue with the `tables` package, not geosnap

Colab tends to cause headaches because it requires pip and doesn't play nicely with conda (if I were you, I'd request anaconda support over there). Pip is pretty unreliable (for exactly this reason), so we only support conda installs for users. I'm going to close this as out of scope, since it seems specific to colab+pip, though feel free to reopen if you run into problems using the recommended install route. Maybe give [codespaces](https://github.com/features/codespaces) or [binder](https://mybinder.org/) a try instead if you need to run in the cloud

**Comment by swagluke** [comment]
Thank you for the fast response.
I retried it today with Google Colab and it's working now. Not sure if Colab had a recent system update or not.

**Comment by knaaptime** [comment]
i think you can thank @smmaurer for that. I think he got a new release of pandana out the door that fixes the outdated `tables` dependency 

anyway, glad its working for you!

**Comment by jGaboardi** [comment]
xref: https://github.com/UDST/pandana/pull/183, https://github.com/UDST/pandana/pull/186
