### ISSUE TITLE
Functions not available

### ISSUE THREAD

**Issue by samueltoro7** [oturns/geosnap#370]
Hi all,

I was trying to follow the "cluster_diagnostics" example but I found some problems to find: **find_k** and **find_region_k** functions to calculate the number of clusters.

I think it might be a version issue. Have someone else faced the same problem?

Best,
Samuel

**Comment by jGaboardi** [comment]
Can you provide some more details:
* Which version of `geosnap` are you running?
* Can you copy and paste *the complete* traceback and error message?

**Comment by knaaptime** [comment]
Hey, thanks for raising this. Those functions are (relatively) new, so they are in the current code base if you do a development install (ie clone and install from source). But they haven't made it into a release yet. 

A release is overdue here so I'll put one together. Though heads up I was thinking of renaming those functions to search_k instead of find_k

**Comment by knaaptime** [comment]
when you do the development install and do `mamba env create -f`, it installs all the geosnap dependencies, but not geosnap itself (because then you'd have the last packaged version, and that doesnt include the functions you are trying to use). Once you have the environment in place, you just need to do `conda activate geosnap`, and `pip install -e . --no-deps`, which will install the latest version from oturns/geosnap@main (and any time you make changes to the local geosnap code, those changes will be available in your environment.

Hope that helps, but i'll also commit some time to getting a new release out the door so that you can do a regular install

**Comment by knaaptime** [comment]
these are now available
